name: flutterapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


# version统一版本名称和版本号，'+'前面的为版本名称，后面的为版本号
version: 1.0.5+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # https://github.com/best-flutter/flutter_swiper/blob/master/README-ZH.md 轮播图组件
  flutter_swiper : ^1.1.6

  # webview插件 （在android9.0以上和ios需配置一些内容）
  # 该插件无法加载网络的异常处理 https://blog.csdn.net/weixin_30642267/article/details/101941152
  flutter_webview_plugin: ^0.4.0

  # 网络请求框架
  dio: ^4.0.0

  # 网络请求框架 cookie管理框架
  dio_cookie_manager: ^2.0.0

  # http缓存库
  dio_http_cache: ^0.3.0

#  # 刷新框架
#  flutter_easyrefresh: ^2.1.5

  # 刷新框架
  pull_to_refresh: ^2.0.0

  # toast框架
  toast: ^0.1.5

  # 文件操作插件
  path_provider: ^2.0.4

  # 简单数据存储插件
  # NSUserDefaults on iOS and macOS, SharedPreferences on Android, etc.
  shared_preferences: ^2.0.7

  # 集成分享 sharesdk
#  sharesdk_plugin: ^1.2.8

  # 事件总线
  event_bus: ^2.0.0

  # 图片选择器
  image_picker: ^0.8.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/lake.jpg
    - images/b01.jpg
    - images/net_error.png

  fonts:
    - family: myIcon
      fonts:
#        - asset: fonts/iconfont.ttf
        - asset: fonts/iconfont2.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
